Api to get invitations info
webf-run/identity pull request #2
Opened 2024-03-23 10:58 UTC by Shevil27

An API that gets invitation details using the code invitation code.

2024-03-31 07:51 UTC, mistyharsh commented on packages/base/src/auth/system.ts
> +  useInvitation: boolean;
Where is this flag required? If not, please remove it.

2024-03-31 07:51 UTC, mistyharsh commented on packages/base/src/auth/invitation.ts
> +}
Add a newline character.

2024-03-31 07:52 UTC, mistyharsh commented on packages/base/src/auth/invitation.ts
> +    // app.post('/claim-invitation', async (c) => {
Remove this not-required commented code.

2024-03-31 07:52 UTC, mistyharsh requested changes
Please address the comments.

2024-04-04 16:48 UTC, ubcharu commented on packages/base/src/auth/invitation.ts
> +    code: z.string(),
Fix indentation in this file.

2024-04-07 04:32 UTC, mistyharsh approved these changes

2024-04-07 04:32 UTC, merged